### ISSUE TITLE
Манер останавливается и не перезапускается автоматически

### ISSUE THREAD

**Issue by nnslvp** [EvgeniyKorepov/Watchdog4DanilaMiner#1]
Было бы круто добавить перезапуск если майнер зависает и нет новых записей

**Comment by EvgeniyKorepov** [comment]
Хорошая идея. Завтра сделаю.

**Comment by EvgeniyKorepov** [comment]
Готово, выкатил новый релиз с заказанным функционалом https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases

**Comment by yahorbukhta** [comment]
@EvgeniyKorepov Теперь майнер не стартует
<img width="1003" alt="Screenshot 2021-12-03 at 13 40 47" src="https://user-images.githubusercontent.com/65916399/144589215-cf8a3ddd-1b5e-4164-bc52-2f48bea1f13d.png">

**Comment by SnUk777** [comment]
Евгений, здраствуйте. Пытаюсь открыть файл Watchdog4DanilaMiner.json что б указать путь, файл не открывается. Подскажите пожалуйста ,что мне делать. Спасибо
![1](https://user-images.githubusercontent.com/83875203/146786753-830fb2e3-fecd-4a0f-8ec6-0c97716dc001.png)

**Comment by EvgeniyKorepov** [comment]
Этот файл не является картинкой, вы должны открыть его в текстовом редакторе, к примеру в блокноте
