### ISSUE TITLE
Не отображает температуру 

### ISSUE THREAD

**Issue by Vavok** [EvgeniyKorepov/Watchdog4DanilaMiner#10]
Не отображает температуру на всех амд картах, но и на одном риге на нвиди тоже не отображает ничего

**Comment by EvgeniyKorepov** [comment]
Мне удалось воспроизвести вашу ошибку. Скорее всего дело в переразгоне одной или нескольких карт. Уберите разгон и попробуйте запустить.

**Comment by 9301039** [comment]
![изображение](https://user-images.githubusercontent.com/13090153/147367328-11bab3a8-27d1-4340-b16c-5271652b5ca8.png)
я думаю это в эту ветку надо, драйвера 472.12 новую версию дров не предлагать!

**Comment by EvgeniyKorepov** [comment]
А попробуйте сделать проще - закинуть в папку с вачдогом свой файл nvml.dll, из папки `C:\Program Files\NVIDIA Corporation\NVSMI\nvml.dll`
Только вачдог сначала закройте

**Comment by Vavok** [comment]
По этому пути нет папки и файла 
В поиске нашёл такой файл, он был в папке widows\system32
Но заменили в папке с вочдогом, ничего не изменилось

**Comment by DervilRus** [comment]
Скорее всего это из за windows 11. У одного компа где win10 все ок, у другого где win11 ничего не показывает. Видяхи одинаковые, дрова одинаковые.

**Comment by DervilRus** [comment]
Подмена на файл nvml.dll из системы ни к чему не привела.

**Comment by EvgeniyKorepov** [comment]
А какая у вас версия драйверов NVidia ?

**Comment by Vavok** [comment]
496.49

**Comment by EvgeniyKorepov** [comment]
> 496.49

Такой версии у меня негде нет, не на чем проверить, везде стоит 472.12

**Comment by DervilRus** [comment]
> А какая у вас версия драйверов NVidia ?

497.29

**Comment by EvgeniyKorepov** [comment]
Сейчас на одном из стендов с Win 10 сменил драйвера на 497.29 - все нормально работает, показывает температуру и все остальное
![image](https://user-images.githubusercontent.com/35364901/147754933-8ddb6c7d-c709-4090-a3bc-5375fb80c34b.png)

**Comment by DervilRus** [comment]
> Сейчас на одном из стендов с Win 10 сменил драйвера на 497.29 - все нормально работает, показывает температуру и все остальное ![image](https://user-images.githubusercontent.com/35364901/147754933-8ddb6c7d-c709-4090-a3bc-5375fb80c34b.png)

Ну мне кажется проблема в Win11, других отличий у двух моих игровых машин нет.

**Comment by DervilRus** [comment]
![Без имени](https://user-images.githubusercontent.com/84242788/147755823-e00b947c-680a-4ecb-aaa7-8c9888ccef64.jpg)

**Comment by EvgeniyKorepov** [comment]
Сделал консольный вариант для проверки, выдаст ошибки если что то не так, попробуйте запустить, и если есть ошибки закиньте их сюда (только не скринами, а текстом - пометьте в консоли, скопируйте и вставьте сюда).
[GPUStatistic_test.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7793149/GPUStatistic_test.zip)

**Comment by DervilRus** [comment]
> Сделал консольный вариант для проверки, выдаст ошибки если что то не так, попробуйте запустить, и если есть ошибки закиньте их сюда (только не скринами, а текстом - пометьте в консоли, скопируйте и вставьте сюда). [GPUStatistic_test.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7793149/GPUStatistic_test.zip)

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 0 | FanSpeed 0 % | Power 0

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage -1 % | Temperature -1 | FanSpeed -1 % | Power -1

LOG : Error nvmlDeviceGetHandleByPciBusId_v2 by ABusIDText=00000000:38:00.0

**Comment by EvgeniyKorepov** [comment]
ага, вот уже понятнее. У вас же не 38 pci разъемов?  ))) А строка 00000000:38:00.0 говорит что видеокарта у вас в PCI разъеме № 38.
Видимо ошибка в определении местонахождения карты, сейчас перепроверю код работы с OpenCL где это определяется.

**Comment by DervilRus** [comment]
> ага, вот уже понятнее. У вас же не 38 pci разъемов? ))) А строка 00000000:38:00.0 говорит что видеокарта у вас в PCI разъеме № 38. Видимо ошибка в определении местонахождения карты, сейчас перепроверю код работы с OpenCL где это определяется.

Нет конечно, это мой игровой пк с одной платой. А другой пк это ПК тещи, там Win10 и цифра меньше.
Еще различие, там где все ок машина на стареньком интеле, где не показывает, там ryzen 5 5600

**Comment by DervilRus** [comment]
Кстати еще одно различие, где все ок у меня интел, где проблема, Ryzen 5 5600x

**Comment by DervilRus** [comment]
Хотя, запускаю Gminer, есть такая строка:
 Started Mining on GPU0: MSI NVIDIA GeForce RTX 3060 12GB [0000:26:00.0]

Тирекс:
20211230 18:35:51 + GPU #0: [00:26.0|2503] MSI GeForce RTX 3060, 12287 MB

ton-pool miner
2021-12-30 18:37:47,331 [INFO] NVIDIA GeForce RTX 3060 on PCI bus 38 slot 0: starting normal mining with hash_solver_4 and 131072 iterations per thread

Данила майнер
2021-12-30 18:44:17,661 | [38] Starting benchmarks for NVIDIA GeForce RTX 3060...

MSI Afterburner:
Видеоадаптер         : NVIDIA GeForce RTX 3060 на процессоре GA106-A
Видеодрайвер         : 497.29
BIOS                 : 94.06.14.00.df
Идентификатор        : VEN_10DE&DEV_2503&SUBSYS_39761462&REV_A1&BUS_38&DEV_0&FN_0
Ключ реестра         : \Registry\Machine\System\CurrentControlSet\Control\Video\{231323AB-6950-11EC-9378-00D861DA908D}\0000
Контроллер VDDC      : Видеодрайвер

GPU-Z:

General
Driver Date	2021-12-15
DCH/UWD Driver	Yes
Registry Path	SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000
Device Location	Bus 38, Device 0, Function 0





Почему то почти везде 38, а вот в некоторых майнерах 26.

**Comment by DervilRus** [comment]
Откат на 3060 mining driver :) (470.05) ничего не меняет.

**Comment by EvgeniyKorepov** [comment]
Все понятно ) 38 и 26 - одно и то же число ) 36 если перевести hex равно 26. Как то я прозевал этот момент в документации что там надо номер PCI в hex формате.
Попробуйте переделанный тест.
[GPUStatistic_test.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7793733/GPUStatistic_test.zip)

**Comment by DervilRus** [comment]
> Все понятно ) 38 и 26 - одно и то же число ) 36 если перевести hex равно 26. Как то я прозевал этот момент в документации что там надо номер PCI в hex формате. Попробуйте переделанный тест. [GPUStatistic_test.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7793733/GPUStatistic_test.zip)

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 45 | FanSpeed 38 % | Power 46

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 45 | FanSpeed 37 % | Power 46

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 44 | FanSpeed 36 % | Power 45

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 44 | FanSpeed 35 % | Power 45

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 44 | FanSpeed 35 % | Power 45

PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 38 Slot 0 | NVIDIA GeForce RTX 3060 | GPU_usage 0 % | Temperature 43 | FanSpeed 35 % | Power 45

Я так понимаю все ок ;) Теперь все супер!!! Эх жалко ваша графическая версия тока с данилой работает ;))))) Консольку можно юзать вообще по сути с любым майнером ;) Универсальный инструмент ;)

**Comment by EvgeniyKorepov** [comment]
Ура! ))) Перечитал документацию https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html и что то не нашел там упоминания о hex. И мой код корректно работал только для GPU в PCI слоте от до 9 включительно )))

Сейчас выкачу обновление вачдога...

**Comment by EvgeniyKorepov** [comment]
Проверьте, нормально работает на новом релизе?

https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.5

**Comment by DervilRus** [comment]
> Проверьте, нормально работает на новом релизе?
> 
> https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.5

Да, спасибо большое. Все отлично.

![Без имени](https://user-images.githubusercontent.com/84242788/147773740-fcbfc694-95b3-4f68-b697-b5528c9105f5.png)
