### ISSUE TITLE
Падает хэш рейт

### ISSUE THREAD

**Issue by BLADLust1** [EvgeniyKorepov/Watchdog4DanilaMiner#11]
Приветствую!
При запуске последней версии вочдога, который с GUI, в статистике пула падает хэшрейт
Пример не GUI вочдога:
Effective hashrate 24h: 16.09 GH/s
Effective hashrate 1h: 17.4 GH/s

Пример последнего вочдога:
Effective hashrate 24h: 12.74 GH/s
Effective hashrate 1h: 12.3 GH/s

Имею два рига, в одном 4 карты, в другом одна карта. И вот такое ощущение что ПК с одной картой не учитывается. И +ко всему на это ПК с одной картой не отображается темп, нагрузка и т.д. По логам он работает, шары ловит.

**Comment by EvgeniyKorepov** [comment]
Скажите адрес кошелька, достаточно последние 10 символов, я посмотрю что происходит в статистике.

**Comment by BLADLust1** [comment]
btCRcxJ_pi6YPL
Сейчас запустил не GUI:
Effective hashrate in 24h: 12.76 GH/s
Effective hashrate in 60m: 18.00 GH/s

**Comment by EvgeniyKorepov** [comment]
Статистику не успел посмотреть - консольная версия затерла данные новой версии (чтоб этого не происходило лучше указывать другие имена ригов). Но вижу что 2021-12-24 12:15:00 у вас снизился хешрейт с 13330,57 до 12928,00 на риге BLAD-Miner. В 2021-12-24 14:29:00 хешрейт на этом риге восстановился до 13146,61. 
Это время когда вы запускали новую версию? 
Какую именно версию вы используете? 
На каких картах было проседание хешрейта? 
Была ли загрузка на всех картах 100%?

Посмотрите диспетчер задач, там должно быть всего два процесса danila-miner.exe, один из них жрет CPU, другой нет. Если вы использовали версию 2.0.1.0 или 2.0.2, то как раз мог произойти двойной запуск майнера и общий хешрейт просесть.

**Comment by BLADLust1** [comment]
На первом риге стоят 3 карты 3080 и 1 1660 -на этом риге загрузка всех карт постоянно скачет, от 0 до 100% если смотреть через диспетчер задач. На компе с одной 3080 такого нет -нагрузка идет от 60 до 100%.
По поводу времени -да, примерно в это время я запускал GUI.
Не понятно на каких картах или риге идет проседание (такое ощущение складывается, что официальная статистика пула перестает видить ПК с одной картой, через GUI все карты показывают премлимый хэш около 4гх и 1.35гх на 1660. А по факту статистики https://tonwhales.com/mining/stats/
Хэш упал до 12гх.
Версия консольного последняя, ГУИ 2.0.1
Двойной запуск бы не получился, если одновременно запустить два майнера, то второй просто выдает ошибку.
Usage,temp, fan все параметры отобрают -1

**Comment by BLADLust1** [comment]
Скрин загрузки рига на 4 карты:
https://ibb.co/Sf5ht7v
Скрин неправильного отображения инфы:
https://ibb.co/WWNrGrQ

**Comment by EvgeniyKorepov** [comment]
> На первом риге стоят 3 карты 3080 и 1 1660 -на этом риге загрузка всех карт постоянно скачет, от 0 до 100% если смотреть через диспетчер задач. На компе с одной 3080 такого нет -нагрузка идет от 60 до 100%. По поводу времени -да, примерно в это время я запускал GUI. Не понятно на каких картах или риге идет проседание (такое ощущение складывается, что официальная статистика пула перестает видить ПК с одной картой, через GUI все карты показывают премлимый хэш около 4гх и 1.35гх на 1660. А по факту статистики https://tonwhales.com/mining/stats/ Хэш упал до 12гх. Версия консольного последняя, ГУИ 2.0.1 Двойной запуск бы не получился, если одновременно запустить два майнера, то второй просто выдает ошибку. Usage,temp, fan все параметры отобрают -1

Статистика на пуле не видит карт, она основывается только на отправленных найденных шарах.
Два майнера параллельно отлично работают, по крайней мере на моих стендах, но общий хешрейт у них меньше одного майнера на 10-15%, скорее всего из за перегрузки CPU.

Версия 2.0.1самая первая, в ней есть несколько критичных багов, которые могут вызывать проблемы подобные вашей, обновитель до последней версии 2.0.3 https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.3

**Comment by BLADLust1** [comment]
Обновил до последней версии. Наблюдаю. 
Вопрос, а за счет чего программа так жрет CPU?

**Comment by EvgeniyKorepov** [comment]
Вачдог не ест CPU, откройте Диспетчер задач и посмотрите кто именно ест CPU
![image](https://user-images.githubusercontent.com/35364901/147751753-7daa182f-c17f-4f23-a2a9-22ea1de5f497.png)
