### ISSUE TITLE
Статтеры\фризы в конце итога 2.0.3

### ISSUE THREAD

**Issue by Akkihi** [EvgeniyKorepov/Watchdog4DanilaMiner#12]
Во время загрузки строки или примерно каждые 10 секунд.
**2021.12.24 17:21:27 2021-12-24 17:21:27,938 | Total system hashrate 729.69 Mhash/s, 10.01s, 0 shares found**
Статтерит\ фризит систему на 1-3 секунды.
Проблема явно возникает в конце подсчета, процессор не бросается в нагрузку, видеокарта amd rx 570 4gb
![image](https://user-images.githubusercontent.com/31794830/147355933-f9a565c1-a55d-4db4-9e98-b3286403ab95.png)

**Comment by EvgeniyKorepov** [comment]
Вам нужно адресовать вопрос разработчику майнера в чате. Майнер хорошо нагружает процессор, это часть вычислительного процесса.
Вачдог почти не ест CPU, доли процента.
