### ISSUE TITLE
6600xt

### ISSUE THREAD

**Issue by furioussv** [EvgeniyKorepov/Watchdog4DanilaMiner#13]
![image](https://user-images.githubusercontent.com/16815334/147384956-6629c40f-bada-47f4-95f8-c840d0d822f9.png)
вот так это работает с RX6600 XT, карта в стоке.

**Comment by EvgeniyKorepov** [comment]
Спасибо за сообщение! В самое ближайшее время проведу тесты на картах AMD, до этого не было возможности...

**Comment by EvgeniyKorepov** [comment]
Проверьте, должно все заработать начиная с этого релиза https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.5

**Comment by furioussv** [comment]
уже проверил, на зеленых ригах (1070/1080) заработало, на 6600хт по прежнему везде -1

**Comment by EvgeniyKorepov** [comment]
> уже проверил, на зеленых ригах (1070/1080) заработало, на 6600хт по прежнему везде -1

А попробуйте запустить на риге с 6600хт диагностическое приложение вот из этого сообщения  https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/issues/10#issuecomment-1003095546

Все что приложение выведет в консоль скопируйте и закиньте сюда. Заранее благодарю.

**Comment by furioussv** [comment]
![image](https://user-images.githubusercontent.com/16815334/147810138-6eda2de8-2298-4290-9650-fe51642f841e.png)

**Comment by EvgeniyKorepov** [comment]
Проверьте как работает в новом релизе https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.6

**Comment by ablom888** [comment]
6800 XT - проблема сохраняется, но стало показывать хешрейт

**Comment by EvgeniyKorepov** [comment]
Попробуйте мой новый майнер https://korepov.com/ton/minerpro/, там я постарался решить все эти проблемы. Но опять же на красных особо не тестировал (их у меня одна всего)))), нужны тестировщики )
