### ISSUE TITLE
Hive OS Devices select

### ISSUE THREAD

**Issue by earthangeltrue** [EvgeniyKorepov/Watchdog4DanilaMiner#15]
How to select specific devices for mining TON in Hive OS? 
I don't understand this command - danila-miner run -d 0:0 -d 2a:00.0 https://server1.whalestonpool.com YOUR_WALLET
May you explain where and how should i write this one with examples, please?

**Comment by earthangeltrue** [comment]
The developer closed an issue without resolving it.

**Comment by earthangeltrue** [comment]
> The developer closed an issue without resolving it.

**Comment by EvgeniyKorepov** [comment]
> The developer closed an issue without resolving it.

Because this is the repository of the **Watchdog4DanilaMiner** application. Not **danila-miner**.

Check out the documentation for the danila-miner on the pool website

**Comment by earthangeltrue** [comment]
There is no repository of danila-miner, just Watchdog4DanilaMiner. The documentation for the danila-miner on the pool website doesn't work in my Hive OS and have no any examples and poor explanations.

**Comment by EvgeniyKorepov** [comment]
> There is no repository of danila-miner, just Watchdog4DanilaMiner. The documentation for the danila-miner on the pool website doesn't work in my Hive OS and have no any examples and poor explanations.

I am not a developer of danila-miner, I can not help you with anything
