### ISSUE TITLE
How Windows uses watchdogs？

### ISSUE THREAD

**Issue by lzy2009** [EvgeniyKorepov/Watchdog4DanilaMiner#16]
Мой Windows 10, не нашел exe на странице загрузки, только 7Z, но этот файл не может быть открыт после загрузки

**Comment by faikuluturk** [comment]
stats.json cannot find 
stats.json cannot find 
stats.json cannot find 
stats.json cannot find

**Comment by lzy2009** [comment]
My Windows 10 didn't find the exe on the download page, only 7Z, but this file can't be opened after downloading

**Comment by EvgeniyKorepov** [comment]
> Мой Windows 10, не нашел exe на странице загрузки, только 7Z, но этот файл не может быть открыт после загрузки

7z это 7zip архив, открывается всеми архиваторами.
Добавил в релизы архив ZIP - https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/latest/download/WD4DanilaMinerGUI.zip
