### ISSUE TITLE
Card error: maybe rerun miner with -t or -i flag 

### ISSUE THREAD

**Issue by Petronikita** [EvgeniyKorepov/Watchdog4DanilaMiner#17]
![image](https://user-images.githubusercontent.com/96838823/147688488-b0b3500b-38ab-459f-ab22-9500f63f7c5f.png)
Циклирует эту ошибку. Не понимаю что необходимо сделать для нормальной работы, так же во время работы фризит всю систему

**Comment by EvgeniyKorepov** [comment]
В первой строке майнер дает вам точную информацию о сути проблемы:
Ошибка карты : попробуйте подобрать параметры -t или -i

Документация по использованию майнера вот тут https://tonwhales.com/docs/miners/danila/cli

Попробуйте добавить параметр "-i 1.2" в файл WD4DanilaMinerGUI.json (откройте в блокноте) в строку "MinerParams", вот так:

```
{
	"MinerVersionOverlap" : "",
	"MinerParams" : "-i 1.2",

	"ConsoleReadTimeoutSec" : 45,
....
```
