### ISSUE TITLE
AMD 6900XT no info in WD4DanilaMinerGUI

### ISSUE THREAD

**Issue by TheXak** [EvgeniyKorepov/Watchdog4DanilaMiner#18]
Проблема такая же, как и в соседнем топике с  6600xt, вся статистика показывает -1 или 0.

GPUStatistic_test:
PlatformID 0 | DeviceID 0 | DeviceNum 0 | PCI Bus 0 Slot 0 | gfx1030 | GPU_usage -1 % | Temperature -1 | FanSpeed -1 % | Power 0
PlatformID 1 | DeviceID 0 | DeviceNum 1 | PCI Bus 8 Slot 0 | NVIDIA GeForce GTX 1060 6GB | GPU_usage 6 % | Temperature 35 | FanSpeed 60 % | Power 11

![image](https://user-images.githubusercontent.com/57081997/147886081-9de7a180-f86f-473f-8201-5989d08eeda7.png)

Перепробовал  каждую библиотеку atiadlxx.dll, что вообще есть на пк, в т.ч. и из стат.теста последнего, изменений нет.
![image](https://user-images.githubusercontent.com/57081997/147886126-6cc7e1ae-0e35-4f32-86d8-aba6fee7b845.png)

Upd. Заметил, что в процессах висит 2 процесса с 2.2.2 майнером, а не 2.3.0, странно это, почему используется более старый при наличии нового в папке(автоскачал) и при этом как либо изменить это не получается.
![image](https://user-images.githubusercontent.com/57081997/147886770-79c05ae6-3b54-4670-b791-365ce28bcce9.png)
При этом если запустить через батник напрямую 2.3.0 версию, то хэш значительно больше, чем на, к примеру, 2.1.4. (2.3.0 = 5.4к, 2.1.4=4.9к), в то же время через watchdog, запускающий, как я вижу, 2.2.2 - получается 4.9к, как и на старом 2.1.4.
![image](https://user-images.githubusercontent.com/57081997/147886865-e13db07c-45c6-4b52-b5f6-411477cc6501.png)

P.S. Чтобы не выносить в отдельную тему - если есть возможность сделать "тёмную тему" в одном из будущих обновлений - было бы замечательно)

**Comment by EvgeniyKorepov** [comment]
1. В следующем релизе думаю будет исправлено. Идентификация карт будет переведена полностью на PCI Bus Id, вместо текущей "Как бог на душу положит" идентификации по номеркам OpenCl.
2. Версия майнера 2.3.0 была отозвана разработчиком по причине не стабильной работы в некоторых системах. Если у вас она работает хорошо, то вы можете использовать ее изменив в файле WD4DanilaMinerGUI.json параметр "MinerVersionOverlap", вбейте нужное значение, к примеру 
`	"MinerVersionOverlap" : "2.3.0",`
3. Интерфейс и тему я пока оставляю на потом, когда будут решены все важные задачи )))

**Comment by EvgeniyKorepov** [comment]
Проверьте как работает в новом релизе https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.6

**Comment by TheXak** [comment]
Теперь показывает хэш и в столбце PCI вместо "0" стоит "6", но с остальной статой всё еще проблемы:
![image](https://user-images.githubusercontent.com/57081997/147928506-5a15d614-e49e-4442-9a0c-c26389607338.png)

**Comment by ablom888** [comment]
Аналогичная проблема. Появился хешрейт, остальных данных нет. Замена dll не помогла. Конфигурация: 4х3080TI (все ок), 1х6800 XT (не отображает данные, кроме хешрейта).

**Comment by EvgeniyKorepov** [comment]
Попробуйте мой новый майнер https://korepov.com/ton/minerpro/, там я постарался решить все эти проблемы. Но опять же на красных особо не тестировал (их у меня одна всего)))), нужны тестировщики )
