### ISSUE TITLE
Изменение макс. нагрузки через WD4DanilaMinerGUI

### ISSUE THREAD

**Issue by TheXak** [EvgeniyKorepov/Watchdog4DanilaMiner#19]
Можно ли используя WD4DanilaMinerGUI выставить определенную нугрузку на карту (например поставить ограничение в 95%)?
Нигде не нашел возможность задать параметры майнинга, как при запуске через обычный батник.
Ну и если нет, то планируется ли данный функционал в будущем?

**Comment by EvgeniyKorepov** [comment]
Файл WD4DanilaMinerGUI.json, параметр MinerParams, прописывайте все что вам нужно.
