### ISSUE TITLE
Need a way to delete rig

### ISSUE THREAD

**Issue by BebopSpikeSpiegel** [EvgeniyKorepov/Watchdog4DanilaMiner#2]
Currently when a rig stopped mining for certain period of time, it will turn red.
But in my opinion, a certain way to **delete** rigs are also needed, to avoid/prevent situations such as misoperations.

Anyway thanks for your contribution

**Comment by BebopSpikeSpiegel** [comment]
Also the most important is, keep the page clean and tidy :)
my page is an obvious example when there's no delete function.

**Comment by EvgeniyKorepov** [comment]
Inactive rigs disappear automatically after 24 hours
