### ISSUE TITLE
Device 0A:00.0 not found.

### ISSUE THREAD

**Issue by fx565656** [EvgeniyKorepov/Watchdog4DanilaMiner#20]
WD4DanilaMinerGUI не верно прописывает ключ(с номерами девайсов) майнеру если номер PCI больше или равен 10 (видимо при переводе в 16-ричный формат). Как следствие лог: Device 0A:00.0 not found.  Возможно "a" в нижнем регистре надо...
При PCI от 0 до 9 всё работает корректно.

![Снимок экрана](https://user-images.githubusercontent.com/97061264/147977129-d3e14dd4-a984-486e-9129-b3db430d5504.jpg)

**Comment by EvgeniyKorepov** [comment]
Попробуйте в командной строку запустить danila-miner.exe с параметрами
 -d 0A:00.0
и
 -d 0a:00.0
может действительно не переваривает верхний регистр. 
Напишите сюда результат, заранее благодарю.

**Comment by EvgeniyKorepov** [comment]
[WD4DanilaMinerGUI.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7804136/WD4DanilaMinerGUI.zip)
Вот версия 2.0.6, но в ней я сделал принудительно в нижний регистр pci bus id, попробуйте

**Comment by fx565656** [comment]
> [WD4DanilaMinerGUI.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7804136/WD4DanilaMinerGUI.zip) Вот версия 2.0.6, но в ней я сделал принудительно в нижний регистр pci bus id, попробуйте

Да всё заработало! )
