### ISSUE TITLE
Тёмный скин и шрифты поменьше.

### ISSUE THREAD

**Issue by fx565656** [EvgeniyKorepov/Watchdog4DanilaMiner#23]
На ригах где не подключен монитор разрешение экрана маленькое и почитать логи затруднительно когда по AnyDesk.
И не хватает темной темы. 
Да простит меня автор, дабы не отвлекать по мелочам, немного допилил под себя (скин, шрифты и чтобы при старте вкладка лог вместо баланса была активна)

[WD4DanilaMinerGUI.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7822773/WD4DanilaMinerGUI.zip)

![image](https://user-images.githubusercontent.com/97061264/148404880-e57eb54e-98c5-4d7a-a474-eeadb0a062a9.png)
[WD4DanilaMinerGUI.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7822773/WD4DanilaMinerGUI.zip)

**Comment by EvgeniyKorepov** [comment]
Добавил стили, уменьшил размер шрифтов, в логах в том числе.
https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/releases/tag/2.0.7
