### ISSUE TITLE
Как вывести монеты в свой кошелек?

### ISSUE THREAD

**Issue by ViktorBystrov72** [EvgeniyKorepov/Watchdog4DanilaMiner#24]
Монеты майнятся, а когда их можно увидеть в официальном кошельке https://wallet.ton.org/ ?
Во вкладке Balance постоянно прибавляется понемногу. 
На сайте со статистикой https://korepov.com Pool balance есть немного, а Wallet balance 0 пишет

**Comment by fx565656** [comment]
> Монеты майнятся, а когда их можно увидеть в официальном кошельке https://wallet.ton.org/ ? <

Вы ошиблись темой, тут оболочка для майнера и она к выводу монет никакого отношения не имеет.
Вывод на кошель делается через телеграмбота @WhalesPoolBot
Тут всё написано: https://tonwhales.com/docs/pool
