### ISSUE TITLE
Device ff:00.0 not found.

### ISSUE THREAD

**Issue by nareshalka** [EvgeniyKorepov/Watchdog4DanilaMiner#25]
При попытке запустить майнинг на видеокарте выскакивает Device ff:00.0 not found. Последняя версия майнера. Майнер запущен от имени администратора.
![image](https://user-images.githubusercontent.com/89643425/148562643-f72110d8-b090-492e-b80e-7badd0ad7a59.png)

Если через Командную строку запустить майнер, работает вроде нормально. 
![image](https://user-images.githubusercontent.com/89643425/148563451-7bb9cb32-9abd-4310-888b-3663fc180d8f.png)

**Comment by EvgeniyKorepov** [comment]
Отключите вторую карту, последняя колонка, кликните по Enabled и все заработает. Майнинг на Intel не имеет смысла и не поддерживается.

P.S. Добавлю в следующий релиз автоматическое отключение таких карт. Спасибо за сообщение.
