### ISSUE TITLE
Found two or more devices with id: 08:00.0

### ISSUE THREAD

**Issue by egotist713** [EvgeniyKorepov/Watchdog4DanilaMiner#29]
![danilahuinya](https://user-images.githubusercontent.com/97874803/149728253-d1d96f37-30a8-4761-9df2-bd080394cb3d.jpg)
как не работала ваша поделка, так и не работает.

**Comment by egotist713** [comment]
Отличная поддержка Евгений. Так держать!

**Comment by EvgeniyKorepov** [comment]
Проблема в вашей системе, у вас две платформы, на каждой зарегистрирован комплект дубликатов, естественно danila-miner.exe не может запустить устройство на PCI BUS 8, потому как их там якобы два. Запустите `danila-miner.exe info` , посмотрите что выдаст.

**Comment by stranger-inzeku** [comment]
![1](https://user-images.githubusercontent.com/97760069/150522836-678ae72a-e60b-4a23-8e8c-3f96764c2910.jpg)
что с этим делать? питон для 7 винды 64 бит установлен, с++ 2015 тоже

**Comment by stranger-inzeku** [comment]
что с этим делать? питон для 7 винды 64 бит установлен, с++ 2015 тоже
![1](https://user-images.githubusercontent.com/97760069/150523323-a60a4668-21a6-4a39-b1e4-47bd045bd3be.jpg)

**Comment by egotist713** [comment]
> Проблема в вашей системе, у вас две платформы, на каждой зарегистрирован комплект дубликатов, естественно danila-miner.exe не может запустить устройство на PCI BUS 8, потому как их там якобы два. Запустите `danila-miner.exe info` , посмотрите что выдаст.

Не надо перекладывать проблему на пользователя, просто честно напишите что вам лень фиксить баг. Все другие майнеры (gminer, t-rex, NBminer) и в частности lolMiner который также может майнить TON проблем в моей системе не видит.

**Comment by EvgeniyKorepov** [comment]
> что с этим делать? питон для 7 винды 64 бит установлен, с++ 2015 тоже ![1](https://user-images.githubusercontent.com/97760069/150523323-a60a4668-21a6-4a39-b1e4-47bd045bd3be.jpg)

Вам нужно обратится к разработчику майнера, попробуйте написать в техподдержку пула https://t.me/tonwhalessupport

**Comment by EvgeniyKorepov** [comment]
> > Проблема в вашей системе, у вас две платформы, на каждой зарегистрирован комплект дубликатов, естественно danila-miner.exe не может запустить устройство на PCI BUS 8, потому как их там якобы два. Запустите `danila-miner.exe info` , посмотрите что выдаст.
> 
> Не надо перекладывать проблему на пользователя, просто честно напишите что вам лень фиксить баг. Все другие майнеры (gminer, t-rex, NBminer) и в частности lolMiner который также может майнить TON проблем в моей системе не видит.

Вы понимаете что ошибку вам выдает майнер? А это репозиторий вачдога и как бы вы не просили меня фиксить баги, я не могу этого сделать, так как не являюсь разработчиком майнера. Попробуйте написать в техподдержку пула https://t.me/tonwhalessupport

**Comment by EvgeniyKorepov** [comment]
Попробуйте новый майнер TonMinerPro https://korepov.com/ton/minerpro/, там эта проблема решена.
