### ISSUE TITLE
Device ff:00.0 not found.

### ISSUE THREAD

**Issue by set8888** [EvgeniyKorepov/Watchdog4DanilaMiner#31]
К майнеру подключены несколько ригов. При подключении через вачдог пишет:
2022.01.23 20:49:26 Use miner version 2.3.1
2022.01.23 20:49:27 Use pool https://pool.services.tonwhales.com
2022.01.23 20:49:27 START
2022.01.23 20:49:29 Device ff:00.0 not found.
В чем проблема и как решить? Благодарю!

**Comment by set8888** [comment]
Вот еще что выяснил, если в этот адрес (https://korepov.com/ton/) ввести свой кошелек то там статистика тоже по нулям показывает хотя по факту майнинг идет и баланс на пуле растет

**Comment by EvgeniyKorepov** [comment]
А в приложении вы выбрали карту, она помечена как enabled?  И какой у нее номер PCI BUS? 
Ваш логи говорят что не возможно запустить карту номером PCI -1, скорее всего это карта Intel или встроенная.
