### ISSUE TITLE
Версия майнера

### ISSUE THREAD

**Issue by TheFreir** [EvgeniyKorepov/Watchdog4DanilaMiner#4]
Было бы неплохо добавить при запуске вывод версии майнера. Например: "Версия 2.1.4".
В консоли майнера при запуске эта информация есть.

**Comment by EvgeniyKorepov** [comment]
Хм, я в упор не вижу информацию о версии danila-miner.exe. Ни в консоли, ни в заголовке окна ее нет.
Хотел сделать автообновление майнера, но не нашел информации о версии
![image](https://user-images.githubusercontent.com/35364901/145152813-10cd88a0-82a8-4924-8b4e-af0c19b1e89f.png)

**Comment by TheFreir** [comment]
Прошу прощения, действительно информации о версии нигде нет.
Ещё хотел предложить при ошибке выводить хоть немного информации о ошибке из консоли, например последнюю строку.

**Comment by TheFreir** [comment]
Ещё, зачем при выводе json на сайте в заголовках тэги < br >? Например: "Last activity< br >(seconds ago)".

**Comment by EvgeniyKorepov** [comment]
> Прошу прощения, действительно информации о версии нигде нет. Ещё хотел предложить при ошибке выводить хоть немного информации о ошибке из консоли, например последнюю строку.

Вот тут есть проблема - или мгновенно реагировать на ошибку и перезапускать майнер, или ждать неопределенное количество времени для получения полной информации. А майнер может и не выдать ничего после ключевого слова, а может начать вываливать кучу ошибок по кругу. Когда остановится и перезапустить его - вопрос. Поэтому я выбрал немедленную реакцию на ошибку. А вы уже, увидев на https://korepov.com/ton/ большое количество перезапусков на риге, остановить ватчдог и запустить майнер отдельно и выяснить причину.

**Comment by EvgeniyKorepov** [comment]
> Ещё, зачем при выводе json на сайте в заголовках тэги < br >? Например: "Last activity< br >(seconds ago)".

Вот блин, мой косяк, забыл про это )))))) Спасибо за сообщение. Сейчас исправлю...

**Comment by EvgeniyKorepov** [comment]
> Ещё, зачем при выводе json на сайте в заголовках тэги < br >? Например: "Last activity< br >(seconds ago)".

Исправил. Надеюсь никому не сломал этим обработку статистики
```
{
	"Rig name": "Far forest",
	"Last activity (seconds ago)": "9",
	"Hashrate": "4593.46",
	"Hashrate average": "4293.15",
	"Shares count": "19",
	"Uptime": "00:59:54",
	"Wrong hash count": "0",
	"Miner restart count": "5"
}
```

**Comment by TheFreir** [comment]
Понял, спасибо.
