### ISSUE TITLE
Проблема с отображением на https://korepov.com/ton/

### ISSUE THREAD

**Issue by motogon** [EvgeniyKorepov/Watchdog4DanilaMiner#5]
Добрый день 

Похоже есть проблема с вачдогом или с отображением на https://korepov.com/ton/
Сейчас заметил на сайте в поле Last activity 15 минут и строка подсвечена красным . 

Хотя визуально майнер работает , каждые 10с +- обновляется информация в консоле .

**Comment by motogon** [comment]
![изображение](https://user-images.githubusercontent.com/12997195/145204735-22739bb4-9739-4753-8eb8-aeaf232af447.png)

**Comment by EvgeniyKorepov** [comment]
Работает майнер или вачдог? Точно вачдог запущен? Баланс в строках вывода обновляется?

**Comment by motogon** [comment]
> Работает майнер или вачдог? Точно вачдог запущен? Баланс в строках вывода обновляется?

работает майнер запущенный вачдогом . 

![изображение](https://user-images.githubusercontent.com/12997195/145242537-ff076634-7a3f-4c2a-88da-ecd624c24ffa.png)
и в это время 
![изображение](https://user-images.githubusercontent.com/12997195/145242639-de5efe1b-c36c-4672-ad09-9d91f5abaa3d.png)

**Comment by motogon** [comment]
баланс обновляется 
![изображение](https://user-images.githubusercontent.com/12997195/145244087-e3282bb7-c15e-476c-b6d6-3b0237845ccb.png)

**Comment by EvgeniyKorepov** [comment]
Напишите адрес своего кошелька, я проверю логи, посмотрим  в чем может быть дело. Если не хотите светить адрес, можете написать только последние 10-12 знаков кошелка.

**Comment by motogon** [comment]
#####################GmxgdjMHasZI8B_5X

**Comment by EvgeniyKorepov** [comment]
Ваша статистика работает нормально, никаких проблем нет.
![image](https://user-images.githubusercontent.com/35364901/145344332-919d6d85-0f56-4f45-8eb2-ef6c101fa12e.png)

**Comment by motogon** [comment]
так проблема в том , что периодически случается , ситуация о которой я писал выше . 
Те часть времени - статистика отображается штатно , но периодически "подвисает" если так можно назвать :)

**Comment by EvgeniyKorepov** [comment]
Учитывая что на сервер статистики льется больше 100 запросов в секунду и никаких проблем не наблюдается, что то на вашей стороне. Может интернет отваливается? 

update:
А когда подвисает, то потом само начинает работать, или вы предпринимаете какие то действия?

**Comment by motogon** [comment]
комп подключен в сеть с 2 независимыми каналами оптики ( оба на мониторинге в забиксе и алармов по ним нет ) , те по интернету скорей всего , проблем быть не должно . Никаких действий не предпринимаю , само "подвисло" само восстановилось .

**Comment by EvgeniyKorepov** [comment]
А в логах что на момент подвисания?

**Comment by motogon** [comment]
[Watchdog4DanilaMiner_2021.12.08.log.zip](https://github.com/EvgeniyKorepov/Watchdog4DanilaMiner/files/7684854/Watchdog4DanilaMiner_2021.12.08.log.zip)

в часы явно зафиксированных проблем, см скриншоты , в логах не увидел ничего криминального

**Comment by EvgeniyKorepov** [comment]
У меня больше нет идей. Сегодня перевел все на гораздо более резвый сервер, с ssd и прочими плюшками. понаблюдайте изменится что то или нет.

**Comment by motogon** [comment]
пока тоже , идеи иссякли , прикрутил забикс к Вашему api . Пусть собираются данные
