### ISSUE TITLE
REQUEST: Linux watchdog

### ISSUE THREAD

**Issue by iceMongus** [EvgeniyKorepov/Watchdog4DanilaMiner#6]
Linux watchdog будет?

**Comment by EvgeniyKorepov** [comment]
Скорее всего нет

**Comment by kostin** [comment]
Привет. А где-то есть документация по параметрам майнера для linux? Выхлоп от майнера, я так понял, можно получать только со стандартного вывода. А какие-то параметры типа для какой из видеокарт запускаться, а для какой нет?
