### ISSUE TITLE
Отключение видеокарт

### ISSUE THREAD

**Issue by d10nn** [EvgeniyKorepov/Watchdog4DanilaMiner#8]
Доброго времени суток
Хотел уточнить есть ли возможность отключать определенные видеокарты в конфиге/майнере?
Есть ли возможность это реализовать?
Спасибо

**Comment by EvgeniyKorepov** [comment]
![image](https://user-images.githubusercontent.com/35364901/146677277-9b0b6b50-c2a0-48a8-baae-7b7f81fcf4eb.png)

**Comment by d10nn** [comment]
Не совсем понятно, что там надо писать..
Допустим есть 5 видеокарт, я хочу отключить вторую. Что необходимо в том поле указать?
Спасибо

**Comment by EvgeniyKorepov** [comment]
Вот документация по майнеру https://tonwhales.com/docs/miners/danila/cli
Так же вы можете получить помощь запустив `danila-miner.exe run -h`

Если кратко, вам нужно узнать номер платформы и номер устройства ваших видеокарт, команда
`danila-miner.exe info`
затем в параметрах вачдога перечислить их, к примеру
`-d 0:0 -d 0:1 -d 0:2 -d 0:4`

P.S. это относится к версии майнера 2.2.0

**Comment by GuRo81** [comment]
Привет, у меня такой же вопрос, майнер 2.2 стоит на Hive OS, прописываю доп. конфигурацию: -d 01:00.0 (для проверки чтобы работала только первая карта). Продолжают работать все. В чем затык?

**Comment by Sheicer** [comment]
А в 2.0.5 этот способ работает?

**Comment by Queritt** [comment]
В 2.0.5 с "MinerParams" : "-d 0:0" выдает ошибку. 
![DM-2](https://user-images.githubusercontent.com/42835693/147856792-e1f993cf-043b-4b4b-9f62-14293c3c3971.jpg)
Как выбрать нужное устройство в 2.0.5?

**Comment by EvgeniyKorepov** [comment]
Увеличьте окно, последняя колонка Status, кликайте на ячейки Enabled

![image](https://user-images.githubusercontent.com/35364901/147981895-b2eaa793-15ac-45d1-8d21-0aefce2479a3.png)
